# Workflow to publish to Firebase App Distribution
name: Publish to Firebase

# Only trigger manually via workflow_dispatch
on:
  workflow_dispatch:

jobs:
  # First job: run unit tests
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK 17 (Temurin distribution)
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      # Execute your Android unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

  # Second job: build APK and upload to Firebase
  firebase_publish:
    name: Build and Upload to Firebase
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      # Re-checkout code at the start of this job
      - uses: actions/checkout@v4

      # Set up JDK again for Gradle
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Install the Android SDK to build the app
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.0

      - uses: gradle/actions/setup-gradle@v4

      # Build the Debug APK with Gradle
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --no-daemon

      # Upload to Firebase App Distribution
      - name: Upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: app/build/outputs/apk/debug/app-debug.apk
