# Workflow name shown in GitHub Actions UI
name: Test and Upload Artifact App

# When to run this workflow:
on:
  # Trigger on any push to 'main'
  push:
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  # First job: run your unit tests
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK 17 (Temurin distribution)
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Execute your Android unit tests
      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

  # Second job: build the APK and upload it
  distribute:
    name: Upload APK as Artifact
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      # Re-checkout code at the start of this job
      - uses: actions/checkout@v4

      # Set up JDK again for Gradle
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # Install the Android SDK to build the app
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.0

      # Build the Debug APK with Gradle
      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --no-daemon

      # Upload the generated Debug APK as a GitHub Actions artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          # The name shown in the Actions UI for this artifact
          name: app-debug-apk
          # Path to the APK file produced by the build
          path: app/build/outputs/apk/debug/app-debug.apk
