name: Deploy App

on:
  push:
    branches:
      - setup-publishing
  workflow_dispatch:

jobs:
  unit_tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    if: ${{ false }}       # TMP disable job for testing
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --no-daemon --stacktrace

  publish:
    name: Publish to Maven Central
    #needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java, OSSRH creds & import GPG key
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Publish artifacts
        run: |
          ./gradlew publishReleasePublicationToMavenCentralRepository --no-daemon --stacktrace \
            -PossrhUsername="${{ secrets.OSSRH_USERNAME }}" \
            -PossrhPassword="${{ secrets.OSSRH_PASSWORD }}" \
            -Psigning.key="${{ secrets.MAVEN_KEY }}" \
            -Psigning.password="${{ secrets.MAVEN_KEY_PASSWORD }}"

  distribute:
    name: Distribute APK
    needs: unit_tests
    runs-on: ubuntu-latest
    if: ${{ false }}       # TMP disable job for testing
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.0

      - name: Build Debug APK
        run: ./gradlew :app:assembleDebug --no-daemon

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: Testers
          file: app/build/outputs/apk/debug/app-debug.apk